### ISSUE TITLE
uncaught exception: this.emit is not a function

### ISSUE THREAD

**Issue by FRYYYYYY** [JoJ123/ioBroker.mihome-airpurifier#36]
After the upgrade to 0.1.1 the following message appears:

![image](https://user-images.githubusercontent.com/13643787/80197360-d04bf080-861e-11ea-8da7-a5de6165953c.png)

**Comment by SoldierOc** [comment]
Me too. 5 Minute Error-Log cycle like yours. Loggin' with debug-level is pointless (no more informations...)

![24-04-_2020_23-08-02](https://user-images.githubusercontent.com/63428971/80257157-927fb400-8680-11ea-9731-c5ea742ca06a.jpg)


Version 0.1.1
node.js 12.16.2
js 3.0.18

**Comment by 7egacy** [comment]
Seme here with Version 0.1.1 / node 10.20.1 / js 3.0.19
Object Buttons to Switch the Mode doesnt work

**Comment by JoJ123** [comment]
Hi @7egacy @SoldierOc @FRYYYYYY I've published a new version 0.1.2 could you test that again. I don't get this error locally. To which device are you connecting?

**Comment by JoJ123** [comment]
@FRYYYYYY @SoldierOc @7egacy 
Try to install it directly from the master branch: 
https://github.com/JoJ123/ioBroker.mihome-airpurifier

**Comment by FRYYYYYY** [comment]
> Hi @7egacy @SoldierOc @FRYYYYYY I've published a new version 0.1.2 could you test that again. I don't get this error locally. To which device are you connecting?

To version 2.

**Comment by FRYYYYYY** [comment]
> @FRYYYYYY @SoldierOc @7egacy
> Try to install it directly from the master branch:
> https://github.com/JoJ123/ioBroker.mihome-airpurifier

Still not working with Version 0.1.4

![FC1CEDB2-DD74-4CC0-BE72-4B0A4971AD0B](https://user-images.githubusercontent.com/13643787/80828884-58656380-8be6-11ea-989c-1210ed6c55b7.png)

**Comment by SoldierOc** [comment]
@JoJ123 Updated to the latest release (0.1.2) - still have the error-code.

Xiaomi Smart Mi Air Purifier 2

**Comment by JoJ123** [comment]
@FRYYYYYY @SoldierOc Can you both please try to install it from GitHub directly.

The version 0.1.5 should work for both of you.

**Comment by SoldierOc** [comment]
Ok. I've tested V0.1.5. unfortunately a new error occoured.

**Comment by JoJ123** [comment]
Can you share the error please? You are using version 2?

SoldierOc <notifications@github.com> schrieb am Fr., 1. Mai 2020, 20:36:

**Comment by JoJ123** [comment]
@SoldierOc I see the error, I will investigate. Can you

**Comment by SoldierOc** [comment]
Sorry, error message wasn't complete. Will this log help you?
https://s12.directupload.net/images/200501/9v8gh2ef.jpg

(Sorry pictureupload@github isn't working for me at the moment -> so external link)

**Comment by JoJ123** [comment]
1. On which hardware are you running iobroker?
2. Which node version are you using? You can check that in cmd with node -v

SoldierOc <notifications@github.com> schrieb am Fr., 1. Mai 2020, 20:41:

**Comment by SoldierOc** [comment]
1. Intel Nuc i3 / Ubuntu 18.04.4 LTS

2. Newest 12.6.3 as recommended in ioBroker

**Comment by 7egacy** [comment]
Adapter Version 0.1.4 zusammen mit dem Air Purifier 2S scheint zwar zu funktionieren (also Mode Switch, aktuelle Infos vom Gerät kommen auch an usw.) aber es erscheint im Log nach kurzer Zeit:

mihome-airpurifier.0 | 2020-05-01 21:02:12.442 | error | at Timer.processTimers (timers.js:223:10)
-- | -- | -- | --
mihome-airpurifier.0 | 2020-05-01 21:02:12.442 | error | at listOnTimeout (timers.js:263:5)
mihome-airpurifier.0 | 2020-05-01 21:02:12.442 | error | at tryOnTimeout (timers.js:300:5)
mihome-airpurifier.0 | 2020-05-01 21:02:12.442 | error | at ontimeout (timers.js:436:11)
mihome-airpurifier.0 | 2020-05-01 21:02:12.442 | error | at Timeout.checkRegularValues [as _onTimeout] (/opt/iobroker/node_modules/iobroker.mihome-airpurifier/build/air-purifier/mi-air-purifier.js:56:14)
mihome-airpurifier.0 | 2020-05-01 21:02:12.442 | error | (549) TypeError: Cannot read property 'power' of undefined
mihome-airpurifier.0 | 2020-05-01 21:02:12.440 | error | (549) uncaught exception: Cannot read property 'power' of undefined

Ich nutze einen Pi4 mit aktuellem Raspbian, Node.js v10.20.1 und js Controler 3.0.20

**Comment by JoJ123** [comment]
@7egacy Bitte einmal die aktuelle Version von GitHub hier installieren (0.1.5)

Ab 2 Uhr heute Nacht sollte die auch direkt in ioBroker zur Verfügung stehen.

**Comment by FRYYYYYY** [comment]
Ich nutze einen RPi 3B. Teste die 0.1.5er und melde mich. 👍

**Comment by JoJ123** [comment]
@SoldierOc Currently I don't have a clue, why you are getting this error. Could you please once completely remove the adapter. Delete the instance & and then remove the local copy of the adapter inside the adapter tab.

Then install it again from GitHub

**Comment by 7egacy** [comment]
> @7egacy Bitte einmal die aktuelle Version von GitHub hier installieren (0.1.5)
> 
> Ab 2 Uhr heute Nacht sollte die auch direkt in ioBroker zur Verfügung stehen.

Jetzt zeigt es mir im Log an:

mihome-airpurifier.0 | 2020-05-01 21:32:33.085 | error | (30687) Wronge device type.
-- | -- | -- | --


Sämtliche Objekte sind ohne Funktion. Nutze den 2S und habe es auch so eingestellt

**Comment by JoJ123** [comment]
@7egacy Do you have access to a pc in the same network with the purifier, where you can install NodeJS?

**Comment by 7egacy** [comment]
Ja, das wäre kein Problem. Kann es ein Windows PC sein?

**Comment by JoJ123** [comment]
Okay perfekt:

https://github.com/JoJ123/miio-test
Dieses Repo bitte einmal als zip herunterladen, dann in dem Verzeichnis wo die package.json liegt `npm install` ausführen, danach `node index`. Sende mir dann bitte die Logs an:
**johannesjaegeroffice@gmail.com**

**Comment by JoJ123** [comment]
@7egacy Habe noch eine Sache vergessen. Bevor du `node index` aufrufst bitte noch mit einem Texteditor die index.js öffnen und IP Adresse und Token anpassen

**Comment by JoJ123** [comment]
Closed with 0.1.6

**Comment by FRYYYYYY** [comment]
Ich würde es gerne testen, aber der Adapter lässt sich bei mir jetzt weder aktualisieren noch installieren...
Die Updates der anderen Adapter funktionieren.

![2FD8B0DE-205B-428A-9C99-018175618DE0](https://user-images.githubusercontent.com/13643787/80859513-eb8faf00-8c61-11ea-9ec2-e3cea6eee7e3.png)

**Comment by JoJ123** [comment]
@FRYYYYYY Please check for that in #37  I've pushed a new version.
